name: whakaari_env
channels:
  - defaults
  - conda-forge
dependencies:
  - tsfresh=0.13.0
  - python=3.7.6
  - imbalanced-learn=0.6.1
  - scikit-learn=0.22
  - obspy=1.1.0
  - corner=2.0.1
  - joblib=0.14.0
  - numpy=1.18.1
  - pandas=0.25.3
  - scipy=1.3.1
  - statsmodels=0.10.2
  - pip
prefix: /anaconda3/envs/whakaari_env
